name: Hourly Sub JSON Update

on:
  schedule:
    - cron: '0 * * * *' # اجرا هر ساعت (دقیقه صفر)
  workflow_dispatch:

jobs:
  convert_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: pip install requests

      - name: Run Converter Script
        run: python converter.py

      - name: Commit and Push
        run: |
          git config --global user.name 'Final Sub Fixer'
          git config --global user.email 'action@github.com'
          # اضافه کردن فایل JSON
          git add sub_config.json
          # بررسی تغییرات و کامیت
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto fix and update JSON sub $(date)" && git push)
